baseurl = "/"
title = "Qtlin.tw blog"
languageCode = "zh-TW"
disqusShortname = "blog-qtlin" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10



[blackfriday]
   hrefTargetBlank = true


[[menu.main]]
    name="Projects"
    weight=2
    url="/projects"

[[menu.main]]
    name="Resume"
    weight=3
    url="http://qtlin.tw"



[author]
    name = "qtlintw"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    # post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    # defaultDescription = "Your default page description"
    # defaultKeywords = "your,default,page,keywords"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    # theme = "theme-base-0b"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = "/static/css/override_.css"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "優雅宅"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-80879951-3"
    gravatarHash = "60c67aaad4f1c453fc912ed7ebaa2f10"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/pinetum"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "https://www.linkedin.com/in/qtlintw"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    